### ISSUE TITLE
Correcciones TP2

### ISSUE THREAD

**Issue by geronimo-palavecino** [Bastian1998/TP2-TDA-Buchwald#1]
Buenas, como están ?
Nuevamente les dejo las correcciones por acá:

1. Recuerden ser un poco más claros con lo que escriben. Tienen oraciones muy largas en las que intentan poner mucha información y termina costando entender que es lo que quieren decir.
2. La ecuación de recurrencia que plantean esta en general bien encaminada y después la idea bien a código, pero tiene un par de fallos que es importante notar:
    - Ustedes definen la variable *j*, pero la misma aparece de la nada dentro de la ecuación, nunca la acotan o indican su dominio (Esto es fundamental ya que la misma cambia dependiendo del)
    - De forma estrictamente matemática, para un *n* > 1 su ecuación genera múltiples soluciones a causa de *j*. Para esto tienen que elegir alguna que realmente constituya el óptimo para dicho *n*.
3. Su ecuación de recurrencia depende de *n* y de *f(n)*. Siendo que *f(n)* depende de *n*, capaz sería más conveniente hacer que la ecuación sea solamente dependiente de *n* (Esto también tiene mas lógica, ya que lo que están optimizando es la cantidad de enemigos eliminados _para un minuto n_ determinado)
4. No esta muy claro su análisis de la ecuación de recurrencia. Estaría bueno que agreguen el análisis del problema que realizaron, que propiedades notaron, y como llegaron a la ecuación.
    - Noten también que mencionan que usando la ecuación de recurrencia se obtiene la secuencia óptima. Esto es incorrecto, ya que la ecuación de recurrencia les otorga el óptimo de enemigos eliminados, a partir de la cual se puede reconstruir la secuencia para llegar a dicho óptimo.
5. Traten de ser mas concisos cuando explican el algoritmo. En el mismo recorren dos listas, luego en la explicación dicen que se recorre una, y después dicen que dos.
6. En el análisis de la variabilidad de los valores dicen que "a igual volumen de datos y distintos valores, los tiempos son iguales". Entiendo que capaz quisieron decir que tienden a ser iguales, pero ojo que no es lo mismo decir "tienden a ser" a decir "son".
    - Sumado a esto, siendo que lo mencionan, hubiese estado interesante que lo grafiquen y lo muestren.
7. En la demostración de optimalidad nunca demuestran los puntos que plantean. (Pasan a hacer un seguimiento de un ejemplo, pero recuerden que un ejemplo no sirve como demostración)
8. Hubiese estado bueno que usasen un ejemplo un poco más largo para mostrar como funciona la ecuación (3 o 4 elementos, como para que se vea bien cuando "se toman las decisiones clave")
9. Ademas de plotear los tiempos de ejecución como puntos, hubiese estado interesante que los unieran y los extrapolaran con otra curva cuadrática, para mostrar bien la tendencia.
10. Recuerden poner en el README.md la forma de ejecución del código, así no hay que tener que estar adivinando como hacerlo. Sumado a esto, no pude hacer funcionar el código para archivos que no posean un nombre diferente a alguno de los que ustedes predefinieron.
11. Algunos puntos respecto al código:
    - Nuevamente, no tiene sentido que en el código tengan un diccionario con los resultados esperados. Si quieren puede agregarlos en otro modulo de testing
    - Podrían pedir solamente el path al archivo que tiene los datos, en vez de pedir el nombre de un archivo que se encuentre en el mismo directorio
    - Siendo que no están trabajando con algoritmo alternativos, no óptimo, no tiene sentido que digan si el resultado es óptimo o no, ya que se espera que siempre sea óptimo.

De todo esto necesito que corrijan los puntos 2, 4. Cualquier otra corrección que quieran implementar suma a la nota.

**Comment by geronimo-palavecino** [comment]
Buenas, como estan ?
Estuve mirando las correcciones que hicieron para la reentrega, y sigue habiendo algunos cosas que tienen que corregir.

1. La nueva ecuación de recurrencia que plantean en el informe es incorrecta. En este caso vuelven a tener el problema de que cada optimo genera multiples soluciones y no eligen ninguna (Solo pusieron el max para el OPT(n-j), el cual, siendo que el min esta "suelto", no acota la selección). No obstante, siendo que cuando me preguntaron por las correcciones y que cambiaron la expresión, voy a asumir que fue un typo.

2. Les menciono nuevamente que cuesta **mucho** entender cual es la idea que estan intentando exponer en las explicaciones. Les pido por favor que la proxima vez sean claros y conciso con las ideas. No traten de dar tantas vueltas para llegar al punto

3. En el tercer párrafo del análisis del problema hay un par de ideas que no estan del todo claras, pero por lo que dan a entender, no son correctas:
    - Dicen que están comparando todos los minutos previos (Asumo que querían referirse a los óptimos de los minutos previos), contra todos los posibles valores de poder actual. No solo que esto no les ayudaría en nada, esto no es lo plasmado en la ecuación de recurrencia
    - Dicen que el algoritmo tiene un tono a backtracking porque se calculan todas las posibles combinaciones. Esto tampoco es correcto, ya que solamente, a partir de los valores óptimos de las oleadas anteriores, estan evaluando que tanto tiempo deberían haber dejado pasar desde una ultima oleada x, para atacar ahora y maximizar su ganancia

4. El seguimiento esta bien, pero no les puedo tomar las imágenes en el informe. Cámbienlas por ecuaciones dentro de latex. Si buscan en internet, hay multitud de formas para insertar ecuaciones estructuradas.

5. No queda claro a que referencia la segunda gráfica, ni como interpretarla

Tienen hasta el 30/5 para corregir estas cosas (Poner bien la ecuación de recurrencia, hacer el texto legible e insertar las ecuaciones del seguimiento)

**Comment by Bastian1998** [comment]
Se actualizo el pdf con la ultima corrección siguiendo las indicaciones.
